NIMBUS_NODES: 0
# external nodes we manually manage
NIMBUS_DEV_NODES: 0
# the path of the source code for the manually managed nodes
# point it to an already existing source tree or
# you will find the oritinal source in the container you can copy also
NIMBUS_SOURCE_PATH: /run/desktop/mnt/host/e/tmp/multinet/nbc
NIMBUS_VALIDATORS: 64
NIMBUS_LOG_LEVEL: INFO;TRACE:switch,multistream

LIGHTHOUSE_NODES: 0
# external nodes we manually manage
LIGHTHOUSE_DEV_NODES: 0
# the path of the source code for the manually managed nodes
# point it to an already existing source tree or
# you will find the oritinal source in the container you can copy also
LIGHTHOUSE_SOURCE_PATH: /run/desktop/mnt/host/e/tmp/multinet/lh
LIGHTHOUSE_VALIDATORS: 64

PRYSM_NODES: 0
# external nodes we manually manage
PRYSM_DEV_NODES: 0
# the path of the source code for the manually managed nodes
# point it to an already existing source tree or
# you will find the oritinal source in the container you can copy also
PRYSM_SOURCE_PATH: /run/desktop/mnt/host/e/tmp/multinet/pry
PRYSM_VALIDATORS: 64

# DEV_NODES should use the <client>-dev-N folders for deposits details
# see respective run_<client> scripts for usage

ETH2STATS_DASHBOARD_HOST: 34.90.31.103
ETH2STATS_DASHBOARD_PORT: 30000
ETH2STATS_SERVER_HOST: 34.90.183.99
ETH2STATS_SERVER_PORT: 30001
# Use it if you expose in GKE
ETH2STATS_DASHBOARD_EXPOSURE_PORT: 80
ETH2STATS_SERVER_EXPOSURE_PORT: 8080

# ETH 2.0 PHASE 1
TEKU_CATALYST_NODES: 5
TEKU_CATALYST_NODES_DEV: 2
ETH_1_BLOCK_HASH: 0x3a3fdfc9ab6e17ff530b57bc21494da3848ebbeaf9343545fded7a18d221ffec

# Ethstats for catalyst
CATALYST_STATS_HOST: catalyst.silesiacoin.com
CATALYST_STATS_LOGIN_SECRET: VIyf7EjWlR49

# Postgres for eth2 beacon chain explorer
POSTGRES_PASSWORD: XbCNE86d6J98
POSTGRES_USER: postgres
POSTGRES_DB: db
PGDATA: /root/multinet/postgresql/data
