apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: teku-catalyst-dev
  labels:
    app: multinet
    tier: teku-catalyst-dev
spec:
  replicas: {{ .Values.TEKU_CATALYST_NODES_DEV }}
  serviceName: teku-catalyst
  selector:
    matchLabels:
      tier: teku-catalyst
  template:
    metadata:
      generateName: teku-catalyst-
      labels:
        tier: teku-catalyst
    spec:
      volumes:
        - name: deposits
          persistentVolumeClaim:
            claimName: deposits-storage
        - name: common-data
          persistentVolumeClaim:
            claimName: common-data
      containers:
        - name: catalyst
          image: silesiacoin/ssc20-client:v001
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /root/multinet/repo/deposits
              name: deposits
            - mountPath: /root/multinet/repo/data
              name: common-data
          command: [ "bash", "-c"]
          ports:
            - containerPort: 8545
            - containerPort: 30303
          args:
            - tail -f /dev/null
          # inject environment variables
          env:
            - name: MULTINET_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MULTINET_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
        - name: teku
          image: silesiacoin/ssc20-client:v001
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /root/multinet/repo/deposits
              name: deposits
            - mountPath: /root/multinet/repo/data
              name: common-data
          command: [ "bash", "-c"]
          ports:
            - containerPort: 9000
            - containerPort: 4000
          args:
            - tail -f /dev/null
          env:
            - name: MULTINET_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MULTINET_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
      initContainers:
        - name: genesis
          image: silesiacoin/ssc20-client:v001
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /root/multinet/repo/deposits
              name: deposits
            - mountPath: /root/multinet/repo/data
              name: common-data
          command: [ "bash", "-c" ]
          args:
            - rm -rf /root/multinet/repo/data/$(MULTINET_POD_NAME); mkdir -p /root/multinet/repo/data/$(MULTINET_POD_NAME); ./teku/bin/teku genesis mock --output-file /root/multinet/repo/data/testnet/genesis.ssz --eth1-block-hash $ETH_1_BLOCK_HASH; echo "$GENESIS_BODY" > /root/multinet/repo/data/testnet/genesis.json; echo "STATIC_NODES" > /root/multinet/repo/data/$(MULTINET_POD_NAME)/static-nodes.json; echo "STATIC_NODES" > /root/multinet/repo/data/$(MULTINET_POD_NAME)/trusted-nodes.json;
          # inject environment variables
          env:
            - name: MULTINET_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MULTINET_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            # Genesis parameters
            - name: NIMBUS_NODES
              value: "{{ .Values.NIMBUS_NODES }}"
            - name: NIMBUS_DEV_NODES
              value: "{{ .Values.NIMBUS_DEV_NODES }}"
            - name: NIMBUS_VALIDATORS
              value: "{{ .Values.NIMBUS_VALIDATORS }}"
            - name: LIGHTHOUSE_NODES
              value: "{{ .Values.LIGHTHOUSE_NODES }}"
            - name: LIGHTHOUSE_DEV_NODES
              value: "{{ .Values.LIGHTHOUSE_DEV_NODES }}"
            - name: LIGHTHOUSE_VALIDATORS
              value: "{{ .Values.LIGHTHOUSE_VALIDATORS }}"
            - name: PRYSM_NODES
              value: "{{ .Values.PRYSM_NODES }}"
            - name: PRYSM_DEV_NODES
              value: "{{ .Values.PRYSM_DEV_NODES }}"
            - name: PRYSM_VALIDATORS
              value: "{{ .Values.PRYSM_VALIDATORS }}"
            - name: GENESIS_BODY
              value: {{ .Files.Get "genesis.json" | toJson }}
            - name: ETH_1_BLOCK_HASH
              value: "{{ .Values.ETH_1_BLOCK_HASH }}"
            - name: STATIC_NODES
              value: {{ .Files.Get "static_nodes.json" | toJson }}
